package report

import (
	"bytes"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/wardbox/tofu-drift/internal/plan"
	"github.com/wardbox/tofu-drift/internal/scan"
	"github.com/wardbox/tofu-drift/internal/state"
)

func ids(fs []Finding) string {
	var s []string
	for _, f := range fs {
		s = append(s, f.ID)
	}
	return fmt.Sprint(s)
}

func TestSort(t *testing.T) {
	now := time.Date(2026, 3, 1, 0, 0, 0, 0, time.UTC)
	older, newer := now.AddDate(0, 0, -300), now.AddDate(0, 0, -100)
	r := New(Scan{Region: "us-east-1"}, nil)
	r.AddLive([]scan.LiveResource{
		{Type: "aws_security_group", Key: "sg-d"},
		{Type: "aws_eip", Key: "eipalloc-c", Idle: "unassociated"},
		{Type: "aws_ebs_volume", Key: "vol-b", Class: "gp3", SizeGB: 100, Created: &older},
		{Type: "aws_instance", Key: "i-a", Class: "t3.large", Created: &newer},
	}, now)
	for _, tc := range []struct{ by, want string }{
		{"age", "[vol-b i-a eipalloc-c sg-d]"}, // oldest first, unknown age last by cost
		{"type", "[vol-b eipalloc-c i-a sg-d]"},
		{"cost", "[i-a vol-b eipalloc-c sg-d]"},
	} {
		if err := r.Sort(tc.by); err != nil || ids(r.Findings) != tc.want {
			t.Errorf("sort %s: %s err %v, want %s", tc.by, ids(r.Findings), err, tc.want)
		}
	}
	if err := r.Sort("size"); err == nil {
		t.Error("unknown sort must error")
	}

	var out bytes.Buffer
	if err := r.WriteUnmanagedTable(&out); err != nil {
		t.Fatal(err)
	}
	if s := out.String(); strings.Contains(s, "Drift") || !strings.HasPrefix(s, "Unmanaged & idle\n") || !strings.Contains(s, "Unmanaged: $") {
		t.Errorf("unmanaged table has only the unmanaged section and footer:\n%s", s)
	}
}

func TestExplain(t *testing.T) {
	now := time.Date(2026, 3, 1, 0, 0, 0, 0, time.UTC)
	created := now.AddDate(0, 0, -10)
	r := New(Scan{Region: "us-east-1"}, []state.Resource{
		{Address: "aws_ebs_volume.used", Type: "aws_ebs_volume", Attributes: map[string]any{"id": "vol-used"}},
	})
	r.AddLive([]scan.LiveResource{
		{Type: "aws_instance", Key: "i-run", ARN: "arn:aws:ec2:us-east-1:1:instance/i-run", Name: "web",
			Tags: map[string]string{"Name": "web", "env": "dev"}, Created: &created, Class: "t3.large", Derived: []string{"vol-run"}},
		{Type: "aws_ebs_volume", Key: "vol-run", Class: "gp3", SizeGB: 10},
		{Type: "aws_eip", Key: "eipalloc-1", Idle: "unassociated"},
		{Type: "aws_ebs_volume", Key: "vol-used", Class: "gp3", SizeGB: 10},
	}, now)
	r.AddDrift([]plan.Drift{{Address: "aws_s3_bucket.logs", Type: "aws_s3_bucket", Deleted: true}})

	var out bytes.Buffer
	if !r.Explain(&out, "i-run") {
		t.Fatal("i-run not explained")
	}
	want := `type:     aws_instance
id:       i-run
arn:      arn:aws:ec2:us-east-1:1:instance/i-run
tags:     Name=web, env=dev
created:  2026-02-19 (10 days ago)
status:   unmanaged
idle:     -
cost:     t3.large $0.0832/h × 730 h = $60.74/mo
          + vol-run: gp3 10 GB × $0.08/GB-mo = $0.80/mo
          = $61.54/mo (estimate)
carbon:   ~1.3 kgCO₂/mo (estimate)
`
	if out.String() != want {
		t.Errorf("explain:\n%s\nwant:\n%s", out.String(), want)
	}

	out.Reset()
	if !r.Explain(&out, "eipalloc-1") || !strings.Contains(out.String(), "idle:     unassociated\n") ||
		!strings.Contains(out.String(), "arn:      -\n") || !strings.Contains(out.String(), "created:  -\n") {
		t.Errorf("idle eip:\n%s", out.String())
	}
	out.Reset()
	if !r.Explain(&out, "aws_s3_bucket.logs") || !strings.Contains(out.String(), "deleted out of band") {
		t.Errorf("drift:\n%s", out.String())
	}
	for _, id := range []string{"vol-used", "vol-run", "nope"} {
		if r.Explain(&out, id) {
			t.Errorf("%s is not a Finding, must not be explained", id)
		}
	}
}

func TestWriteImports(t *testing.T) {
	r := New(Scan{Region: "us-east-1"}, []state.Resource{
		{Address: "aws_ebs_volume.m", Type: "aws_ebs_volume", Attributes: map[string]any{"id": "vol-m"}},
	})
	r.AddLive([]scan.LiveResource{
		{Type: "aws_ebs_volume", Key: "vol-a", Name: "Scratch Disk!"},
		{Type: "aws_ebs_volume", Key: "vol-b", Name: "scratch disk"},
		{Type: "aws_instance", Key: "i-1"},
		{Type: "aws_eip", Key: "eipalloc-9", Name: "9 lives"},
		{Type: "aws_ebs_volume", Key: "vol-m", Idle: "unattached"},
	}, time.Now())

	var out bytes.Buffer
	if err := r.WriteImports(&out, []string{"vol-a", "vol-b", "i-1", "eipalloc-9"}); err != nil {
		t.Fatal(err)
	}
	want := `# Generated by tofu-drift. Addresses are placeholders: rename them before apply.
# Then run: tofu plan -generate-config-out=generated.tf

import {
  to = aws_ebs_volume.scratch_disk
  id = "vol-a"
}

import {
  to = aws_ebs_volume.scratch_disk_2
  id = "vol-b"
}

import {
  to = aws_instance.i-1
  id = "i-1"
}

import {
  to = aws_eip._9_lives
  id = "eipalloc-9"
}
`
	if out.String() != want {
		t.Errorf("imports:\n%s\nwant:\n%s", out.String(), want)
	}
	for _, id := range []string{"vol-m", "nope"} {
		out.Reset()
		if err := r.WriteImports(&out, []string{"vol-a", id}); err == nil || out.Len() != 0 {
			t.Errorf("%s: want an error and no output, got %v %q", id, err, out.String())
		}
	}
}
