// Package pricing turns a live resource into a monthly USD Estimate from
// static tables embedded in the binary. Never queried live. Reserved
// instances and savings plans are ignored: every rate is on-demand.
package pricing

import (
	_ "embed"
	"encoding/json"

	"github.com/wardbox/tofu-drift/internal/scan"
)

//go:embed ebs.json
var ebsJSON []byte

//go:embed instances.json
var instancesJSON []byte

// ebs is USD per GB-month by region, then volume type. Unlisted regions fall
// back to us-east-1.
// ponytail: hack/pricing refreshes only the ten instance-table regions; the rest are hand-seeded.
var ebs map[string]map[string]float64

// instances is generated by hack/pricing for EC2, RDS and ElastiCache classes.
var instances struct {
	VCPU map[string]int `json:"vcpu"`
	// Hourly is on-demand USD per hour by region, then instance class.
	Hourly map[string]map[string]float64 `json:"hourly"`
}

// HoursPerMonth turns hourly rates and power into monthly figures.
const HoursPerMonth = 730

func init() {
	if err := json.Unmarshal(ebsJSON, &ebs); err != nil {
		panic(err)
	}
	if err := json.Unmarshal(instancesJSON, &instances); err != nil {
		panic(err)
	}
}

// ebsRate is the USD per GB-month for a volume type in region.
func ebsRate(region, class string) float64 {
	rates, ok := ebs[region]
	if !ok {
		rates = ebs["us-east-1"]
	}
	return rates[class]
}

// hourly is the on-demand USD per hour for an instance class in region.
// Regions without a table use us-east-1 and report approx.
func hourly(region, class string) (usd float64, approx bool) {
	rates, ok := instances.Hourly[region]
	if !ok {
		rates = instances.Hourly["us-east-1"]
	}
	return rates[class], !ok
}

// VCPU is the vCPU count of an EC2, RDS (db.*) or ElastiCache (cache.*)
// instance class; 0 if unknown.
func VCPU(class string) int { return instances.VCPU[class] }

// Monthly is the USD/mo Estimate for r in region; 0 for unpriced types.
// approx is true when the region has no price table and us-east-1 was used.
func Monthly(region string, r scan.LiveResource) (usd float64, approx bool) {
	switch r.Type {
	case "aws_ebs_volume":
		return r.SizeGB * ebsRate(region, r.Class), false
	case "aws_instance":
		if r.Stopped {
			return 0, false
		}
		h, approx := hourly(region, r.Class)
		return h * HoursPerMonth, approx
	}
	return 0, false
}
