// Package pricing turns a live resource into a monthly USD Estimate from
// static tables embedded in the binary. Never queried live. Reserved
// instances and savings plans are ignored: every rate is on-demand.
package pricing

import (
	_ "embed"
	"encoding/json"

	"github.com/wardbox/tofu-drift/internal/scan"
)

//go:embed ebs.json
var ebsJSON []byte

//go:embed instances.json
var instancesJSON []byte

//go:embed flat.json
var flatJSON []byte

// ebs is USD per GB-month by region, then volume type. Unlisted regions fall
// back to us-east-1.
// ponytail: hack/pricing refreshes only the ten instance-table regions; the rest are hand-seeded.
var ebs map[string]map[string]float64

// flat is the flat per-resource rates by region (USD per hour, or per
// GB-month for snapshots), seeded and refreshed like ebs.
var flat map[string]map[string]float64

// instances is generated by hack/pricing for EC2, RDS and ElastiCache classes.
var instances struct {
	VCPU map[string]int `json:"vcpu"`
	// Hourly is on-demand USD per hour by region, then instance class.
	Hourly map[string]map[string]float64 `json:"hourly"`
}

// HoursPerMonth turns hourly rates and power into monthly figures.
const HoursPerMonth = 730

func init() {
	if err := json.Unmarshal(ebsJSON, &ebs); err != nil {
		panic(err)
	}
	if err := json.Unmarshal(instancesJSON, &instances); err != nil {
		panic(err)
	}
	if err := json.Unmarshal(flatJSON, &flat); err != nil {
		panic(err)
	}
}

// rate looks key up in a by-region table, falling back to us-east-1.
func rate(table map[string]map[string]float64, region, key string) float64 {
	rates, ok := table[region]
	if !ok {
		rates = table["us-east-1"]
	}
	return rates[key]
}

// lbRate names the flat rate for each aws_lb class.
var lbRate = map[string]string{"application": "alb_hour", "network": "nlb_hour"}

// hourly is the on-demand USD per hour for an instance class in region.
// Regions without a table use us-east-1 and report approx.
func hourly(region, class string) (usd float64, approx bool) {
	rates, ok := instances.Hourly[region]
	if !ok {
		rates = instances.Hourly["us-east-1"]
	}
	return rates[class], !ok
}

// VCPU is the vCPU count of an EC2, RDS (db.*) or ElastiCache (cache.*)
// instance class; 0 if unknown.
func VCPU(class string) int { return instances.VCPU[class] }

// Monthly is the USD/mo Estimate for r in region; 0 for unpriced types.
// approx is true when the region has no price table and us-east-1 was used.
func Monthly(region string, r scan.LiveResource) (usd float64, approx bool) {
	switch r.Type {
	case "aws_ebs_volume":
		return r.SizeGB * rate(ebs, region, r.Class), false
	case "aws_ebs_snapshot":
		return r.SizeGB * rate(flat, region, "snapshot_gb_month"), false
	case "aws_eip":
		return rate(flat, region, "eip_hour") * HoursPerMonth, false
	case "aws_nat_gateway":
		return rate(flat, region, "nat_gateway_hour") * HoursPerMonth, false
	case "aws_lb":
		return rate(flat, region, lbRate[r.Class]) * HoursPerMonth, false
	case "aws_elb":
		return rate(flat, region, "clb_hour") * HoursPerMonth, false
	case "aws_instance":
		if r.Stopped {
			return 0, false
		}
		h, approx := hourly(region, r.Class)
		return h * HoursPerMonth, approx
	}
	return 0, false
}
