// Package pricing turns a live resource into a monthly USD Estimate from
// static tables embedded in the binary. Never queried live. Reserved
// instances and savings plans are ignored: every rate is on-demand.
package pricing

import (
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/wardbox/tofu-drift/internal/scan"
)

//go:embed ebs.json
var ebsJSON []byte

//go:embed instances.json
var instancesJSON []byte

//go:embed flat.json
var flatJSON []byte

// ebs is USD per GB-month by region, then volume type. Unlisted regions fall
// back to us-east-1.
// ponytail: hack/pricing refreshes only the ten instance-table regions; the rest are hand-seeded.
var ebs map[string]map[string]float64

// flat is the flat per-resource rates by region (USD per hour, or per
// GB-month for snapshots), seeded and refreshed like ebs.
var flat map[string]map[string]float64

// instances is generated by hack/pricing for EC2, RDS and ElastiCache classes.
var instances struct {
	VCPU map[string]int `json:"vcpu"`
	// Hourly is on-demand USD per hour by region, then instance class.
	Hourly map[string]map[string]float64 `json:"hourly"`
}

// HoursPerMonth turns hourly rates and power into monthly figures.
const HoursPerMonth = 730

func init() {
	if err := json.Unmarshal(ebsJSON, &ebs); err != nil {
		panic(err)
	}
	if err := json.Unmarshal(instancesJSON, &instances); err != nil {
		panic(err)
	}
	if err := json.Unmarshal(flatJSON, &flat); err != nil {
		panic(err)
	}
}

// rate looks key up in a by-region table, falling back to us-east-1.
func rate(table map[string]map[string]float64, region, key string) float64 {
	rates, ok := table[region]
	if !ok {
		rates = table["us-east-1"]
	}
	return rates[key]
}

// lbRate names the flat rate for each aws_lb class.
var lbRate = map[string]string{"application": "alb_hour", "network": "nlb_hour"}

// hourly is the on-demand USD per hour for an instance class in region.
// Regions without a table use us-east-1 and report approx.
func hourly(region, class string) (usd float64, approx bool) {
	rates, ok := instances.Hourly[region]
	if !ok {
		rates = instances.Hourly["us-east-1"]
	}
	return rates[class], !ok
}

// VCPU is the vCPU count of an EC2, RDS (db.*) or ElastiCache (cache.*)
// instance class; 0 if unknown.
func VCPU(class string) int { return instances.VCPU[class] }

// Monthly is the USD/mo Estimate for r in region; 0 for unpriced types.
// approx is true when the region has no price table and us-east-1 was used.
func Monthly(region string, r scan.LiveResource) (usd float64, approx bool) {
	usd, approx, _ = estimate(region, r)
	return usd, approx
}

// Math is the cost math behind Monthly, e.g. "gp3 100 GB × $0.08/GB-mo = $8.00/mo".
func Math(region string, r scan.LiveResource) string {
	usd, approx, basis := estimate(region, r)
	s := fmt.Sprintf("%s = $%.2f/mo", basis, usd)
	if approx {
		s += " (≈ us-east-1 price)"
	}
	return s
}

func estimate(region string, r scan.LiveResource) (usd float64, approx bool, basis string) {
	perGB := func(prefix string, rate float64) (float64, bool, string) {
		return r.SizeGB * rate, false, fmt.Sprintf("%s%g GB × $%g/GB-mo", prefix, r.SizeGB, rate)
	}
	perHour := func(prefix string, rate float64, approx bool) (float64, bool, string) {
		return rate * HoursPerMonth, approx, fmt.Sprintf("%s$%g/h × %d h", prefix, rate, HoursPerMonth)
	}
	switch r.Type {
	case "aws_ebs_volume":
		return perGB(r.Class+" ", rate(ebs, region, r.Class))
	case "aws_ebs_snapshot":
		return perGB("", rate(flat, region, "snapshot_gb_month"))
	case "aws_eip":
		return perHour("", rate(flat, region, "eip_hour"), false)
	case "aws_nat_gateway":
		return perHour("", rate(flat, region, "nat_gateway_hour"), false)
	case "aws_lb":
		return perHour(r.Class+" ", rate(flat, region, lbRate[r.Class]), false)
	case "aws_elb":
		return perHour("", rate(flat, region, "clb_hour"), false)
	case "aws_s3_bucket", "aws_dynamodb_table":
		return 0, false, "size unknown"
	case "aws_eks_cluster":
		// Standard-support control plane, the same in every region.
		return perHour("control plane ", 0.10, false)
	case "aws_instance", "aws_db_instance", "aws_elasticache_cluster", "aws_elasticache_replication_group":
		if r.Stopped {
			return 0, false, r.Class + " stopped, no compute charge"
		}
		h, approx := hourly(region, r.Class)
		usd, approx, basis := perHour(r.Class+" ", h, approx)
		if n := Nodes(r); n > 1 {
			return usd * float64(n), approx, fmt.Sprintf("%s × %d nodes", basis, n)
		}
		return usd, approx, basis
	}
	return 0, false, "not priced"
}

// Nodes is how many instances of r's class are billed.
func Nodes(r scan.LiveResource) int { return max(r.Nodes, 1) }
